apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.name }}-nginx
  labels:
    app.kubernetes.io/name: {{ .Values.config.name }}-nginx
    app.kubernetes.io/part-of: {{ .Values.config.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
      matchLabels:
          app.kubernetes.io/name: {{ .Values.config.name }}-nginx
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.config.name }}-nginx
        app.kubernetes.io/part-of: {{ .Values.config.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Values.config.name }}-nginx
        {{ if eq .Values.config.env "prod"}}
          image: "{{ .Values.config.registryBase }}/{{ .Values.config.projectName }}-nginx:latest"
        {{ else }}
          image: "{{ .Values.config.registryBase }}/{{ .Values.config.projectName }}-nginx:{{ .Values.config.env }}"
        {{ end }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: PHP_SERVICE
              value: {{ .Values.config.name }}-php
            - name: NGINX_HOST
              value: {{ .Values.config.name }}-php
            - name: BACKENDS
              value: {{ .Values.config.name }}-php
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
