apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.name }}-php
  labels:
    app.kubernetes.io/name: {{ .Values.config.name }}-php
    app.kubernetes.io/part-of: {{ .Values.config.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.config.name }}-php
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.config.name }}-php
        app.kubernetes.io/part-of: {{ .Values.config.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Values.config.name }}-php
        {{ if eq .Values.config.env "prod"}}
          image: "{{ .Values.config.registryBase }}/{{ .Values.config.projectName }}-php:latest"
        {{ else }}
          image: "{{ .Values.config.registryBase }}/{{ .Values.config.projectName }}-php:{{ .Values.config.env }}"
        {{ end }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: JWT_SECRET_KEY
              value: '%kernel.project_dir%/config/jwt/private.pem'
            - name: JWT_PUBLIC_KEY
              value: '%kernel.project_dir%/config/jwt/public.pem'
            - name: JWT_PASSPHRASE
              value: 'bafe1dc254b45471754c221081f874aa' #@todo this should be a variable
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-proxies
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-name
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-version
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: APP_ID
              valueFrom:
                    configMapKeyRef:
                        name: {{ template "fullname" . }}
                        key: app-id
            - name: APP_DOMAIN
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: app-domain
            - name: APP_CACHE
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: cache      
            - name: AUTH_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-auth
            - name: AUDITTRAIL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-audittrail
            - name: NOTIFICATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-notification
            - name: APP_WEB
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-web
            - name: APP_SUBPATH_ROUTING
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-subpath-routing
            - name: APP_SUBPATH
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-subpath 
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
            - name: APP_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: app_application_key
            - name: APP_DIGISPOOF_LOCATION
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: digispoof-location
            - name: APP_EHERKENNING_LOCATION
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: eherkenning-location
          {{ if .Values.redis.enabled }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: redis-port
            {{-end }}
            - name: APP_URL
              value: https://{{ $.Values.ingress.domain }}/{{ $.Values.ingress.path }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
